### ISSUE TITLE
Expose prefix and base fields

### ISSUE THREAD

**Issue by jonnyschaefer** [nvkp/turtle#26]
Hello,

I just noticed that some ontologies define prefixes that are actually not used in the turtle file.
I do not know if that is often intended or not, but this can be really handy to find related turtle files.
I could think of other use cases where knowing the base IRI might be helpful.

With the current unmarshalling there is no way to see the declared base and prefixes (and its only possible to guess those, that are used).

I do not know where it would be the right place to expose this information.

I think only exporting the fileds `prefixes` and `base` in `scanner.Scanner` is possible, but not optimal, as the manual use of `scanner` is a bit too low level.

I could also think of the possibility that `Unmarshal()` returns an additional info struct, containing a copy of prefixes and base.
But I do not know if my use case justifies the latter changes.

Do you think that this API would be too confusing -  returning some data in a fixed format, while simultaneously filling custom user defined data structures?

**Comment by nvkp** [comment]
Hi, I exposed the prefixes and the base from the `scanner.Scanner` in the tag [v1.2.1](https://github.com/nvkp/turtle/tree/v1.2.1). I did not want the function `Unmarshal` to change the signature, because the current signature is a standard Golang way for parser APIs and also adding a returning field would break the backwards compatibility. You can get the prefixes and the base of a file like this:

```golang
s := scanner.New(scannedFile)

for s.Next() {
    _ = s.Triple()
}

base := s.Base()
prefixes := s.Prefixes()
```
